FROM node:12-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

#RUN apk add --update python krb5 krb5-libs gcc make g++ krb5-dev

RUN mkdir -p /usr/src/app
RUN mkdir /.npm
RUN mkdir /.config

WORKDIR /usr/src/app

COPY ./ /usr/src/app/


RUN npm install


#RUN npm install supervisor -g

WORKDIR /usr/src/app


CMD npm install && npm run dev
