#!/bin/bash

input="$1"

if [ "$input" == "auth" ] || [ -z "$input" ]; then
	echo "Deploying AUTH";
	#git subtree push --force --prefix auth-service https://git.heroku.com/comp412-auth.git master
	git push https://git.heroku.com/comp412-auth.git `git subtree split --prefix auth-service master`:master --force
fi

if [ "$input" == "game" ] || [ -z "$input" ]; then
	echo "Deploying GAME";
	#git subtree push --force --prefix game-manager https://git.heroku.com/comp412-game.git master
	git push https://git.heroku.com/comp412-game.git `git subtree split --prefix game-manager master`:master --force
fi

